// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQC8J17F-AAZs1jYApPhk0-Pr0O9dTrdY',
    appId: '1:698183548491:web:aa93df767e8ba63d0097ce',
    messagingSenderId: '698183548491',
    projectId: 'api-internship',
    authDomain: 'api-internship.firebaseapp.com',
    storageBucket: 'api-internship.appspot.com',
    measurementId: 'G-NH97KCE5DV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7mOdfgcfsFH7ElAILyJHZC4JGdGu3U1s',
    appId: '1:698183548491:android:3806086169a00b220097ce',
    messagingSenderId: '698183548491',
    projectId: 'api-internship',
    storageBucket: 'api-internship.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZtgGgsmFs4iJvLOlzufKxAkfpFuOR5KY',
    appId: '1:698183548491:ios:2cf2bea52d4e2b4e0097ce',
    messagingSenderId: '698183548491',
    projectId: 'api-internship',
    storageBucket: 'api-internship.appspot.com',
    iosClientId: '698183548491-9njs7ifh6d42qcot9n3r5gbdf668o5bi.apps.googleusercontent.com',
    iosBundleId: 'com.example.api',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZtgGgsmFs4iJvLOlzufKxAkfpFuOR5KY',
    appId: '1:698183548491:ios:9178468a48463cbb0097ce',
    messagingSenderId: '698183548491',
    projectId: 'api-internship',
    storageBucket: 'api-internship.appspot.com',
    iosClientId: '698183548491-5u9d0rndtdk5caaa12g00oh5ib63ojtv.apps.googleusercontent.com',
    iosBundleId: 'com.example.api.RunnerTests',
  );
}
